config/routes.rb
Rails.application.routes.draw do
  #ランディングページのルーティング
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  # ユーザーCRUD機能のルーティング
  devise_for :users, controllers: {
    registrations: "users/registrations",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :users, only:[:index, :show]

  # イベントCRUD機能のルーティング
  resources :events

  # イベント参加機能のルーティング
  resources :event_participants, only: [:index, :show, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  # imageuploaderマウント
  mount_uploader :event_image, ImageUploader
  # バリデーション
  validates :title, presence: true
  validates :started_at, presence: true
  validates :closed_at, presence: true
  validates :venue_name, presence: true
  validates :venue_address, presence: true
  validates :venue_url, presence: true
  # アソシエーション
  belongs_to :user
  has_many :event_participants , dependent: :destroy
  has_many :participate_users, through: :event_participants, source: :user
end

app/models/event_participant.rb
class EventParticipant < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # imageuploaderマウント
  mount_uploader :image, ImageUploader

  # アソシエーション
  has_many :events, dependent: :destroy
  has_many :event_participants, dependent: :destroy
  has_many :participate_events, through: :event_participants, source: :event

  # バリデーション
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: true
  before_validation { email.downcase! }

  # deviseメソッド
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,:omniauthable, omniauth_providers: %i(google)

  # oauthメソッド
  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.find_for_google(auth)
    user = User.find_by(email: auth.info.email)
    unless user
      user = User.new(name: auth.info.name,
                      email: auth.info.email,
                      provider: auth.provider,
                      uid:      auth.uid,
                      password: Devise.friendly_token[0, 20],
                                   )
    end
    user.save
    user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    #ログイン済みの場合は
    user_path(current_user)
  end
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image, :image_cache])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :image, :image_cache])
  end
end

app/controllers/event_participants_controller.rb
class EventParticipantsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @participants = current_user.participate_events
  end
  def show
    @participants = EventParticipant.where(event_id: @current_event)
  end

  def create
    current_user.event_participants.create(event_id: params[:event_id])
    redirect_to events_url, notice: "イベントに参加しました"
  end

  def destroy
    current_user.event_participants.find_by(id: params[:id]).destroy
    redirect_to events_url, notice: "イベントの参加を取り消しました"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :check_event_host, only: [:edit,:update,:destroy]
  before_action :authenticate_user!
  def index
    @events = Event.where(release: true).where('started_at >= ?', DateTime.now).includes(:user).order('started_at ASC')
    @search = @events.ransack(params[:q])
    @events = @search.result
  end

  def show
    @participant = current_user.event_participants.find_by(event_id: @event.id)
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  def update
      if @event.update(event_params)
        redirect_to @event, notice: 'Event was successfully updated.'
      else
        render :edit
      end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(
        :title,
        :started_at,
        :closed_at,
        :venue_name,
        :venue_address,
        :venue_url,
        :event_image,
        :event_image_cache,
        :note,
        :release
        )
    end

    def check_event_host
      if current_user.id != @event.user_id
        redirect_to event_path(@event), notice: "イベントの編集・削除は運営者のみが可能です。"
      end
    end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google
    @user = User.find_for_google(request.env['omniauth.auth'])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "google") if is_navigational_format?
    else
      session['devise.google_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def build_resource(hash={})
    hash[:uid] = User.create_unique_string
    super
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id), notice: '他ユーザーの情報は閲覧できません。'
    end
    @events = (current_user.participate_events) + (current_user.events)

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_participants_helper.rb
module EventParticipantsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/views/events/_event.html.erb
  <%= link_to event_path(event), class: "event_link" do %>
    <div class="event_image_thumbnail">
      <% if event.event_image.url %>
        <%= image_tag event.event_image.url %>
      <% else %>
        <%= image_tag 'no_image.jpg' %>
      <% end %>
    </div>

    <div class="event_infomation">
      <ul>
        <li><%= event.title %></li>
        <li>開催：<%= l event.started_at,format: :long %></li>
        <li><%= "運営：#{event.user.name}" %></li>
        <% if current_user.id == event.user_id %>
          <li>
            <div class="tag">
              <%= image_tag 'b4.png', class:'tag_image tag_host' %>
              <p class="tag_text">
                あなたが主催者です
              </p>
            </div>
          </li>
        <% end %>
      </ul>

      <% if event.participate_users.include?(current_user) %>
        <div class="tag">
          <%= image_tag 'b7.png', class:'tag_image' %>
          <p class="tag_text">
            参加済み
          </p>
        </div>
      <% end %>
    </div>
  <% end %>

app/views/events/_form.html.erb
<div class="form_container">
  <%= form_with(model: event, local: true) do |form| %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= event.errors.count %> 件のエラーがあります:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form_main">
      <table>
        <tr>
          <th><%= form.label :title%></th>
          <td><%= form.text_field :title %></td>
        </tr>
        <tr>
          <th><%= form.label :started_at %></th>
          <td><%= form.datetime_select :started_at,{minute_step: 10} %></td>
        </tr>
        <tr>
          <th><%= form.label :closed_at %></th>
          <td><%= form.datetime_select :closed_at,{minute_step: 10}  %></td>
        </tr>
        <tr>
          <th><%= form.label :venue_name %></th>
          <td><%= form.text_field :venue_name %></td>
        </tr>
        <tr>
          <th><%= form.label :venue_address %></th>
          <td><%= form.text_field :venue_address %></td>
        </tr>
        <tr>
          <th><%= form.label :venue_url %></th>
          <td><%= form.text_field :venue_url %></td>
        </tr>
        <tr>
          <th><%= form.label :event_image %></th>
          <td>
            <%= form.file_field :event_image %>
            <%= image_tag(event.event_image.url) if event.event_image && event.event_image.url %>
            <%= form.hidden_field :image_cache %>
          </td>
        </tr>
        <tr>
          <th><%= form.label :note %></th>
          <td><%= form.text_area :note %></td>
        </tr>
        <tr>
          <th><%= form.label :release %></th>
            <td>
              <%= form.radio_button :release, true  %>
              <%= form.label :release, "公開する", {value: true, style: "display: inline-block;"} %>

              <%= form.radio_button :release, false %>
              <%= form.label :release, "公開しない", {value: false, style: "display: inline-block;"} %>
            </td>
        </tr>
      </table>
      <div class="actions">
        <%= form.submit %>
      </div>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<h1 class="page_top">Editing Event</h1>

<%= render 'form', event: @event %>

<p><%= link_to 'Show', @event, class:"btn-flat-double-border" %>  
<%= link_to 'Back', events_path, class:"btn-flat-double-border" %>

app/views/events/index.html.erb
<div class="page_top">
  <h2>イベント一覧</h2>
  <div class="event_search">
    <h3>イベント検索</h3>
    <%= search_form_for @search do |f| %>
      <div class="field" id="title">
        <%= f.label :title_cont, "タイトル（部分一致）" %>
        <%= f.search_field :title_cont %>
      </div>
      <div class="field" id="started_at" >
        <%= f.label :started_at_gteq, "開始日時"%>
        <% if @search.started_at_gteq.present?  %>
          <%= f.text_field :started_at_gteq, class: %Q(date-picker), value: "#{ l @search.started_at_gteq, format: :date}" %>
        <% else %>
          <%= f.text_field :started_at_gteq, class: %Q(date-picker) %>
        <% end %>
        <%= f.label :started_at_lteq_end_of_day, " 〜 " %>
        <% if @search.started_at_lteq_end_of_day.present?  %>
          <%= f.text_field :started_at_lteq_end_of_day, class: %Q(date-picker), value: "#{ l @search.started_at_lteq_end_of_day, format: :date}" %>
        <% else %>
          <%= f.text_field :started_at_lteq_end_of_day, class: %Q(date-picker) %>
        <% end %>
      </div>
      <div class="field" id="user_name">
        <%= f.label :user_name_cont, "運営ユーザー（部分一致）" %>
        <%= f.search_field :user_name_cont %>
      </div>

      <%= f.submit %>
    <% end %>

  </div>

  
</div>

<div class="event_main">
  <% @events.each do |event| %>
    <%= render 'event', event: event %>
  <% end %>
</div>

app/views/events/new.html.erb
<h1 class="page_top">New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path, class:"btn-flat-double-border" %>

app/views/events/show.html.erb
<div class="event_container">
  <div class="event_main">
    <div class="event_image">
      <% if @event.event_image.url %>
        <%= image_tag @event.event_image.url %>
      <% else %>
        <%= image_tag "no_image.jpg" %>
      <% end %>
    </div>
    <ul>
      <li>
        <%= Event.human_attribute_name('title') %>:
        <%= @event.title %>
      </li>
      <li>
        <%= Event.human_attribute_name('user_id') %>:
        <%= @event.user.name %>
      </li>
      <li>
        <%= Event.human_attribute_name('started_at') %>:
        <%= l @event.started_at, format: :long %>
      </li>
      <li>
        <%= Event.human_attribute_name('closed_at') %>:
        <%= l @event.closed_at, format: :long %>
      </li>
      <li>
        <%= Event.human_attribute_name('venue_name') %>:
        <%= @event.venue_name %>
      </li>
      <li>
        <%= Event.human_attribute_name('venue_address') %>:
        <%= @event.venue_address %>
      </li>
      <li>
        <%= Event.human_attribute_name('venue_url') %>:
        <%= @event.venue_url %>
      </li>
      <li>
        <%= Event.human_attribute_name('note') %>:
        <%= @event.note %>
      </li>
      <li>
        <%= Event.human_attribute_name('release') %>:
        <%= @event.release ? "公開" : "未公開" %>
      </li>
    </ul>
  </div>

  <% if current_user.id != @event.user_id %>
    <% if @participant.present? %>
      <%= link_to '参加を解除する', event_participant_path(id: @participant.id), method: :delete, class: 'submit' %>
    <% else %>
      <%= link_to '参加する', event_participants_path(event_id: @event.id), method: :post, class: 'submit' %>
    <% end %>
  <% else %>
    <p><%= link_to 'Edit', edit_event_path(@event), class:"btn-flat-double-border"  %></p>
  <% end %>
  <p> <%= link_to 'Back', events_path, class:"btn-flat-double-border"  %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
  </head>

  <body>
    <header>
      <div class="header_container">
        <div class="header_left">
          <% if user_signed_in? %>
            <span id="menu_switch" class="header_item btn-flat-double-border">メニュー</span>
          <% end %>
          <h2>Event Manager</h2>
        </div>
        <div class="header_right">
          <% if user_signed_in? %>
            <%= link_to 'イベント新規作成', new_event_path, class: "btn-flat-double-border" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "header_item btn-flat-double-border" %>
          <% else %>
            <%= link_to "新規登録", new_user_registration_path, class: "header_item btn-flat-double-border" %>
            <%= link_to "ログイン", new_user_session_path, class: "header_item btn-flat-double-border" %>
          <% end %>
        </div>
      </div>
    </header>
    <main>
      <% if user_signed_in? %>
        <div class="side_menu">
          <ul>
            <li><%= link_to "イベント一覧", events_path %></li>
            <li><%= link_to "マイページ", user_path(current_user.id) %></li>
            <% if current_user.provider == "" %>
              <li><%= link_to 'ユーザー情報を編集', edit_user_registration_path %></li>
            <% end %>
          </ul>
            <div class="side_menu_item"></div>
        </div>
      <% end %>
      <div class="main_container">
        <div class="flash_message">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title">Week <%= calendar.week_number %></span>
    <%else%>
        <span class="calendar-title">Week <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <%end%>
        <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &block) %>
              <% else %>
                <% block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/index.html.erb
<h2>ユーザー</h2>
<% @users.each do |user| %>
  <% if user.id != current_user.id %>
    <li>
      <div class="item">
        <%= link_to user.name, user %>
        <%= link_to 'メッセージ', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: :post %>
      </div>
    </li>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1 class="page_top"><%= @user.name %>さんのマイページ</h1>

  <div class="calendar border_double">
    <h3>参加・主催予定イベント一覧</h3>
    <%= month_calendar(attribute: :started_at, events: @events) do |date, events| %>
      <%= date.to_s(:date) %>

      <% events.each do |event| %>
        <div>
          <%= link_to event.title, event_path(event) %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>